#pragma once

#include <Audio/AudioBuffer.hpp>
#include <Audio/AudioDevice.hpp>
#include <Audio/AudioSource.hpp>
#include <Core/Application.hpp>
#include <Core/Core.hpp>
#include <Core/EntryPoint.hpp>
#include <Core/Input.hpp>
#include <Core/Log.hpp>
#include <Core/TimeStamp.hpp>
#include <Events/TextInput.hpp>
#include <GameObjects/Components/Components.hpp>
#include <GameObjects/GameObjects.hpp>
#include <GameObjects/Node.hpp>
#include <GameObjects/NodeFactory.hpp>
#include <Helper.hpp>
#include <ImGui/ImGuiConsoleSink.hpp>
#ifdef AERO_EDITOR
  #include <ImGui/ImGuiLayer.hpp>
#endif
#include <Layers/Layer.hpp>
#include <Math/Math.hpp>
#include <Networking/NetworkManager.hpp>
#include <Networking/Packet.hpp>
#include <Networking/TCPClient.hpp>
#include <Networking/TCPServer.hpp>
#include <Project/FileDialogs.hpp>
#include <Project/Project.hpp>
#include <Project/SaveScene.hpp>
#include <Project/SceneManager.hpp>
#include <Renderer/BufferLayout.hpp>
#include <Renderer/Color.hpp>
#include <Renderer/FrameBuffer.hpp>
#include <Renderer/IndexBuffer.hpp>
#include <Renderer/RenderCommand.hpp>
#include <Renderer/Renderer.hpp>
#include <Renderer/Renderer2D.hpp>
#include <Renderer/RendererAPI.hpp>
#include <Renderer/Shader.hpp>
#include <Renderer/Texture.hpp>
#include <Renderer/VertexArray.hpp>
#include <Renderer/VertexBuffer.hpp>
#include <Renderer/View.hpp>
#include <Renderer/ViewController.hpp>
#include <Scene/Entity.hpp>
#include <Scene/Scene.hpp>
#include <Scene/SceneComponent.hpp>
#include <Scripting/ScriptManager.hpp>
